package com.model;

/**
 * TCatelog generated by MyEclipse Persistence Tools
 */

public class TCatelog implements java.io.Serializable
{
	private Integer catelogId;
	private String catelogName;
	private String catelogDel;
	
	
	public Integer getCatelogId()
	{
		return catelogId;
	}
	public void setCatelogId(Integer catelogId)
	{
		this.catelogId = catelogId;
	}
	public String getCatelogName()
	{
		return catelogName;
	}
	public void setCatelogName(String catelogName)
	{
		this.catelogName = catelogName;
	}
	public String getCatelogDel()
	{
		return catelogDel;
	}
	public void setCatelogDel(String catelogDel)
	{
		this.catelogDel = catelogDel;
	}

}