package com.model;

/**
 * TLiuyan generated by MyEclipse Persistence Tools
 */

public class TComment implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String comment;

	private String cstart;
	
	private String ctime;
	
	private TGoods goods;
	
	private TUser user;
	private String creply;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getCstart() {
		return cstart;
	}

	public void setCstart(String cstart) {
		this.cstart = cstart;
	}

	public String getCtime() {
		return ctime;
	}

	public void setCtime(String ctime) {
		this.ctime = ctime;
	}

	public TGoods getGoods() {
		return goods;
	}

	public void setGoods(TGoods goods) {
		this.goods = goods;
	}

	public TUser getUser() {
		return user;
	}

	public void setUser(TUser user) {
		this.user = user;
	}

	public String getCreply() {
		return creply;
	}

	public void setCreply(String creply) {
		this.creply = creply;
	}

	

}