package com.model;

/**
 * TGoods generated by MyEclipse Persistence Tools
 */

public class TGoods implements java.io.Serializable,Comparable<TGoods>
{

	private Integer goodsId;
	private String goodsName;
	private String author;
	private String publisher;
	private String isbn;

	private String publishtime;	
	private String goodsMiaoshu;
	private String goodsYangshi;
	private String goodsPic;
	private Integer goodsShichangjia;
	private Integer goodsTejia;
	private Integer goodsCatelogId;
	private Integer goodsNum;
	private String goodsDel;
	
	private Integer xiaoliang;
	
	
	
	public String getGoodsYangshi() {
		return goodsYangshi;
	}
	public void setGoodsYangshi(String goodsYangshi) {
		this.goodsYangshi = goodsYangshi;
	}
	
	public Integer getGoodsId()
	{
		return goodsId;
	}
	public void setGoodsId(Integer goodsId)
	{
		this.goodsId = goodsId;
	}
	
	public String getGoodsName()
	{
		return goodsName;
	}
	public void setGoodsName(String goodsName)
	{
		this.goodsName = goodsName;
	}
	
	
	public String getPublisher()
	{
		return publisher;
	}


	public void setPublisher(String publisher)
	{
		this.publisher = publisher;
	}

	
	
	public String getAuthor()
	{
		return author;
	}


	public void setAuthor(String author)
	{
		this.author = author;
	}
	
	public String getIsbn()
	{
		return isbn;
	}


	public void setIsbn(String isbn)
	{
		this.isbn = isbn;
	}


	public String getPublishtime()
	{
		return publishtime;
	}


	public void setPublishtime(String publishtime)
	{
		this.publishtime = publishtime;
	}
	
	
	
	
	
	
	
	
	
	
	
	
	
	public String getGoodsMiaoshu()
	{
		return goodsMiaoshu;
	}
	public void setGoodsMiaoshu(String goodsMiaoshu)
	{
		this.goodsMiaoshu = goodsMiaoshu;
	}
	public String getGoodsPic()
	{
		return goodsPic;
	}
	public void setGoodsPic(String goodsPic)
	{
		this.goodsPic = goodsPic;
	}
	public Integer getGoodsShichangjia()
	{
		return goodsShichangjia;
	}
	public void setGoodsShichangjia(Integer goodsShichangjia)
	{
		this.goodsShichangjia = goodsShichangjia;
	}
	public Integer getGoodsTejia()
	{
		return goodsTejia;
	}
	public void setGoodsTejia(Integer goodsTejia)
	{
		this.goodsTejia = goodsTejia;
	}
	
	public Integer getGoodsCatelogId()
	{
		return goodsCatelogId;
	}
	public void setGoodsCatelogId(Integer goodsCatelogId)
	{
		this.goodsCatelogId = goodsCatelogId;
	}
	public String getGoodsDel()
	{
		return goodsDel;
	}
	public void setGoodsDel(String goodsDel)
	{
		this.goodsDel = goodsDel;
	}
	public Integer getXiaoliang() {
		return xiaoliang;
	}
	public void setXiaoliang(Integer xiaoliang) {
		this.xiaoliang = xiaoliang;
	}
	@Override
	public int compareTo(TGoods o) {	
		return this.getXiaoliang().compareTo(o.getXiaoliang())*-1;
	}
	public Integer getGoodsNum() {
		return goodsNum;
	}
	public void setGoodsNum(Integer goodsNum) {
		this.goodsNum = goodsNum;
	}
	

	
}