package com.model;

/**
 * TOrder generated by MyEclipse Persistence Tools
 */

public class TOrder implements java.io.Serializable
{

	private Integer orderId;
	private String orderBianhao;
	private String orderDate;
	private String odderSonghuodizhi;
	private String fkstatus;
	private String odderFukuangfangshi;
	private int orderJine=0;
	private Integer orderUserId;
	
	
	public Integer getOrderId()
	{
		return orderId;
	}
	public void setOrderId(Integer orderId)
	{
		this.orderId = orderId;
	}
	public String getOrderBianhao()
	{
		return orderBianhao;
	}
	public void setOrderBianhao(String orderBianhao)
	{
		this.orderBianhao = orderBianhao;
	}
	public String getOrderDate()
	{
		return orderDate;
	}
	public void setOrderDate(String orderDate)
	{
		this.orderDate = orderDate;
	}
	public String getOdderSonghuodizhi()
	{
		return odderSonghuodizhi;
	}
	public void setOdderSonghuodizhi(String odderSonghuodizhi)
	{
		this.odderSonghuodizhi = odderSonghuodizhi;
	}
	public String getOdderFukuangfangshi()
	{
		return odderFukuangfangshi;
	}
	public void setOdderFukuangfangshi(String odderFukuangfangshi)
	{
		this.odderFukuangfangshi = odderFukuangfangshi;
	}
	public String getfkstatus() {
		return this.fkstatus;
	}

	public void setfkstatus(String fkstatus) {
		this.fkstatus = fkstatus;
	}
	public int getOrderJine()
	{
		return orderJine;
	}
	public void setOrderJine(int orderJine)
	{
		this.orderJine = orderJine;
	}
	public Integer getOrderUserId()
	{
		return orderUserId;
	}
	public void setOrderUserId(Integer orderUserId)
	{
		this.orderUserId = orderUserId;
	}

}